{
  pkgs,
  ...
}:
{
  # Import the hardware configuration (automatically generated by NixOS), the system configuration module (contains default settings across all hosts), and the user configuration for 'zacml'
  imports = [
    /etc/nixos/hardware-configuration.nix
    ../../modules/system.nix

    ../../users/zacml/user.nix
  ];

  # Bootloader
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # System name
  networking.hostName = "zacml";

  # Allow internet access
  networking.networkmanager.enable = true;

  # Initialize xserver for graphical interface
  # displaylink is used for the docking station
  services.xserver.enable = true;
  services.xserver.videoDrivers = [
    "displaylink"
    "modesetting"
  ];

  # Enable GNOME
  services.displayManager.gdm.enable = true;
  services.desktopManager.gnome.enable = true;

  # Keyboard layout
  services.xserver.xkb = {
    layout = "us";
    variant = "";
  };

  # Allow for printing
  services.printing.enable = true;

  # Enable PipeWire for audio
  services.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  # Disable GNOME core apps that are not needed, aside from the terminal
  # Also exclude gnome-tour which is just bloat
  services.gnome.core-apps.enable = false;
  environment.gnome.excludePackages = with pkgs; [
    gnome-tour
  ];
  programs.gnome-terminal.enable = true;

  # Set the state version for the system configuration
  system.stateVersion = "25.05";
}
